<template>
<div class="bg-gradient-to-tr from-green-500 to-yellow-500 text-gray-100 font-light">
  <div class="relative flex justify-center items-center">
    <h1 class="max-md:text-3xl text-5xl py-10">VimVentures Wiki</h1>
  </div>
  <div class="relative md:grid md:grid-cols-2 md:gap-10 md:px-8 pt-8 pb-32 bg-gradient-to-t from-gray-900 to-transparent">
    <a href="docs">
      <div class="bg-gray-900 max-w-md rounded overflow-hidden shadow-lg shadow-gray-800 p-4 h-64">
        <h2 class="text-lg font-extrabold">VimVentures Code Documentation</h2>
        <p class="pt-2 pr-8">Code documentation generated by Doxygen.</p>
      </div>
    </a>
    <a href="markdown">
      <div class="bg-gray-900 max-w-md rounded overflow-hidden shadow-lg shadow-gray-800 p-4 h-64">
        <h2 class="text-lg font-extrabold">Development Journal</h2>
        <p class="pt-2 pr-8">All development notes and planning is written in Vimwiki markdown, openly accessable and updated reguluarly.</p>
      </div>
    </a>
    <a href="https://github.com/Ofthemasses/VimVentures">
      <div class="bg-gray-900 max-w-md rounded overflow-hidden shadow-lg shadowgray-800 p-4 h-64">
        <h2 class="text-lg font-extrabold">Repository</h2>
        <p class="pt-2 pr-8">The VimVentures repository hosted on GitHub.</p>
      </div>
    </a>
    <a href="uni">
      <div class="bg-gray-900 max-w-md rounded overflow-hidden shadow-lg shadow-gray-800 p-4 h-64">
        <h2 class="text-lg font-extrabold">BE(Hons) Resources</h2>
        <p class="pt-2 pr-8">VimVentures is also my for my honours level engineering project, resources and files are openly accessable.</p>
      </div>
    </a>
  </div>
</div>
</template>

<script>
export default {
  name: "VimVentures"
}
</script>
