name: Deploy to SFTP

on:
  push:
    branches:
      - main  # Change this to your main branch name

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Node.js
        uses: actions/setup-node@v2
        with:
          node-version: 14  # Choose the appropriate Node.js version

      - name: Install dependencies
        run: npm install

      - name: Build
        run: npm run build

      - name: Set-Up SSH Key
        run: |
          mkdir -p ~/.ssh
          echo "{{ secrets.SFTP_PEM_PRIVATE_KEY }}" > ~/.ssh/id_rsa.pem
          chmod 600 ~/.ssh/id_rsa.pem
          ssh-keyscan -p ${{ secrets.PORT }} -t rsa ${{ secrets.SFTP_SERVER }} >> ~/.ssh/known_hosts
          
      - name: Deploy via SFTP
        run: |
          scp -i ~/.ssh/id_rsa.pem -P ${{ secrets.PORT }} -r ./build ${{ secrets.SFTP_USERNAME }}@${{ secrets.SFTP_SERVER }}:${{ secrets.HOST_PATH }}
